Script started on 2024-10-12 22:43:39+03:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="191" LINES="42"]
7]2;max@localhost.localdomain:~/vagrant/vg3]1;localhost.localdomain8max@localhost:~/vagrant/vg3> vagrant up
[0mBringing machine 'Debian12-inetRouter' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-inetRouter2' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-centralRouter' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-centralServer' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-office1Router' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-office2Router' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-office1Server' up with 'libvirt' provider...[0m
[0mBringing machine 'Debian12-office2Server' up with 'libvirt' provider...[0m
[1;33m==> Debian12-inetRouter: You assigned a static IP ending in ".1" to this machine.
==> Debian12-inetRouter: This is very often used by the router and can cause the
==> Debian12-inetRouter: network to not work properly. If the network doesn't work
==> Debian12-inetRouter: properly, try changing this IP.[0m
[1;33m==> Debian12-office2Router: You assigned a static IP ending in ".1" to this machine.
==> Debian12-office2Router: This is very often used by the router and can cause the
==> Debian12-office2Router: network to not work properly. If the network doesn't work
==> Debian12-office2Router: properly, try changing this IP.[0m
[1;33m==> Debian12-centralRouter: You assigned a static IP ending in ".1" to this machine.
==> Debian12-centralRouter: This is very often used by the router and can cause the
==> Debian12-centralRouter: network to not work properly. If the network doesn't work
==> Debian12-centralRouter: properly, try changing this IP.[0m
[1;33m==> Debian12-office1Router: You assigned a static IP ending in ".1" to this machine.
==> Debian12-office1Router: This is very often used by the router and can cause the
==> Debian12-office1Router: network to not work properly. If the network doesn't work
==> Debian12-office1Router: properly, try changing this IP.[0m
[1;33m==> Debian12-centralRouter: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-centralRouter: generating a local metadata for the box with a version to allow better handling.
==> Debian12-centralRouter: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1;33m==> Debian12-office2Server: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-office2Server: generating a local metadata for the box with a version to allow better handling.
==> Debian12-office2Server: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1;33m==> Debian12-centralServer: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-centralServer: generating a local metadata for the box with a version to allow better handling.
==> Debian12-centralServer: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1m==> Debian12-centralRouter: Creating image (snapshot of base box volume).[0m
[1;33m==> Debian12-office1Router: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-office1Router: generating a local metadata for the box with a version to allow better handling.
==> Debian12-office1Router: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1;33m==> Debian12-office1Server: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-office1Server: generating a local metadata for the box with a version to allow better handling.
==> Debian12-office1Server: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1m==> Debian12-office1Server: Creating image (snapshot of base box volume).[0m
[1;33m==> Debian12-office2Router: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-office2Router: generating a local metadata for the box with a version to allow better handling.
==> Debian12-office2Router: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1;33m==> Debian12-inetRouter: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-inetRouter: generating a local metadata for the box with a version to allow better handling.
==> Debian12-inetRouter: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1m==> Debian12-centralRouter: Creating domain with the following settings...[0m
[1m==> Debian12-centralRouter:  -- Name:              vg3_Debian12-centralRouter[0m
[1m==> Debian12-centralServer: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office2Router: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office1Router: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office2Server: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office2Router: Creating domain with the following settings...[0m
[1m==> Debian12-centralRouter:  -- Title:             Debian12-centralRouter[0m
[1m==> Debian12-office2Server: Creating domain with the following settings...[0m
[1m==> Debian12-inetRouter: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office2Server:  -- Name:              vg3_Debian12-office2Server[0m
[1m==> Debian12-office1Server: Creating domain with the following settings...[0m
[1m==> Debian12-office1Server:  -- Name:              vg3_Debian12-office1Server[0m
[1m==> Debian12-office1Server:  -- Title:             Debian12-office1Server[0m
[1m==> Debian12-office2Router:  -- Name:              vg3_Debian12-office2Router[0m
[1m==> Debian12-centralRouter:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. centralRouter[0m
[1m==> Debian12-office2Router:  -- Title:             Debian12-office2Router[0m
[1m==> Debian12-inetRouter: Creating domain with the following settings...[0m
[1;33m==> Debian12-inetRouter2: No version detected for /home/max/vagrant/images/debian12, using timestamp to watch for modifications. Consider
==> Debian12-inetRouter2: generating a local metadata for the box with a version to allow better handling.
==> Debian12-inetRouter2: See https://www.vagrantup.com/docs/boxes/format#box-metadata for further details.[0m
[1m==> Debian12-office2Server:  -- Title:             Debian12-office2Server[0m
[1m==> Debian12-office1Router: Creating domain with the following settings...[0m
[1m==> Debian12-office1Server:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. office1Server[0m
[1m==> Debian12-centralServer: Creating domain with the following settings...[0m
[1m==> Debian12-office2Router:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. office2Router[0m
[1m==> Debian12-office2Router:  -- Domain type:       kvm[0m
[1m==> Debian12-inetRouter2: Creating image (snapshot of base box volume).[0m
[1m==> Debian12-office2Router:  -- Cpus:              1[0m
[1m==> Debian12-office2Server:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. office2Server[0m
[1m==> Debian12-inetRouter2: Creating domain with the following settings...[0m
[1m==> Debian12-office2Router:  -- Feature:           acpi[0m
[1m==> Debian12-office1Server:  -- Domain type:       kvm[0m
[1m==> Debian12-centralRouter:  -- Domain type:       kvm[0m
[1m==> Debian12-inetRouter:  -- Name:              vg3_Debian12-inetRouter[0m
[1m==> Debian12-office2Server:  -- Domain type:       kvm[0m
[1m==> Debian12-office1Router:  -- Name:              vg3_Debian12-office1Router[0m
[1m==> Debian12-inetRouter2:  -- Name:              vg3_Debian12-inetRouter2[0m
[1m==> Debian12-centralServer:  -- Name:              vg3_Debian12-centralServer[0m
[1m==> Debian12-office2Router:  -- Feature:           apic[0m
[1m==> Debian12-centralRouter:  -- Cpus:              1[0m
[1m==> Debian12-office1Server:  -- Cpus:              1[0m
[1m==> Debian12-inetRouter:  -- Title:             Debian12-inetRouter[0m
[1m==> Debian12-office2Server:  -- Cpus:              1[0m
[1m==> Debian12-office1Router:  -- Title:             Debian12-office1Router[0m
[1m==> Debian12-inetRouter2:  -- Title:             Debian12-inetRouter2[0m
[1m==> Debian12-centralServer:  -- Title:             Debian12-centralServer[0m
[1m==> Debian12-inetRouter2:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. inetRouter2[0m
[1m==> Debian12-office2Router:  -- Feature:           pae[0m
[1m==> Debian12-office1Server:  -- Feature:           acpi[0m
[1m==> Debian12-inetRouter:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. inetRouter[0m
[1m==> Debian12-office2Router:  -- Clock offset:      utc[0m
[1m==> Debian12-office1Router:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. office1Router[0m
[1m==> Debian12-centralRouter:  -- Feature:           acpi[0m
[1m==> Debian12-centralServer:  -- Description:       Виртуальная машина на базе дистрибутива Debian Linux. centralServer[0m
[1m==> Debian12-inetRouter2:  -- Domain type:       kvm[0m
[1m==> Debian12-office1Server:  -- Feature:           apic[0m
[1m==> Debian12-inetRouter2:  -- Cpus:              1[0m
[1m==> Debian12-inetRouter:  -- Domain type:       kvm[0m
[1m==> Debian12-inetRouter:  -- Cpus:              1[0m
[1m==> Debian12-centralRouter:  -- Feature:           apic[0m
[1m==> Debian12-office1Router:  -- Domain type:       kvm[0m
[1m==> Debian12-centralRouter:  -- Feature:           pae[0m
[1m==> Debian12-office2Server:  -- Feature:           acpi[0m
[1m==> Debian12-office1Server:  -- Feature:           pae[0m
[1m==> Debian12-inetRouter2:  -- Feature:           acpi[0m
[1m==> Debian12-office2Router:  -- Memory:            1024M[0m
[1m==> Debian12-inetRouter:  -- Feature:           acpi[0m
[1m==> Debian12-inetRouter:  -- Feature:           apic[0m
[1m==> Debian12-office1Router:  -- Cpus:              1[0m
[1m==> Debian12-centralRouter:  -- Clock offset:      utc[0m
[1m==> Debian12-office2Server:  -- Feature:           apic[0m
[1m==> Debian12-office1Server:  -- Clock offset:      utc[0m
[1m==> Debian12-inetRouter2:  -- Feature:           apic[0m
[1m==> Debian12-office1Server:  -- Memory:            1024M[0m
[1m==> Debian12-inetRouter2:  -- Feature:           pae[0m
[1m==> Debian12-inetRouter:  -- Feature:           pae[0m
[1m==> Debian12-office1Router:  -- Feature:           acpi[0m
[1m==> Debian12-inetRouter:  -- Clock offset:      utc[0m
[1m==> Debian12-office2Server:  -- Feature:           pae[0m
[1m==> Debian12-office1Router:  -- Feature:           apic[0m
[1m==> Debian12-centralServer:  -- Domain type:       kvm[0m
[1m==> Debian12-office1Server:  -- Management MAC:    52:54:00:27:28:87[0m
[1m==> Debian12-inetRouter2:  -- Clock offset:      utc[0m
[1m==> Debian12-inetRouter2:  -- Memory:            1024M[0m
[1m==> Debian12-inetRouter:  -- Memory:            1024M[0m
[1m==> Debian12-office2Router:  -- Management MAC:    52:54:00:27:28:86[0m
[1m==> Debian12-office2Router:  -- Loader:            [0m
[1m==> Debian12-office1Router:  -- Feature:           pae[0m
[1m==> Debian12-office2Router:  -- Nvram:             [0m
[1m==> Debian12-office2Router:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-office2Router:  -- Storage pool:      default[0m
[1m==> Debian12-office1Server:  -- Loader:            [0m
[1m==> Debian12-inetRouter:  -- Management MAC:    52:54:00:27:28:83[0m
[1m==> Debian12-office2Server:  -- Clock offset:      utc[0m
[1m==> Debian12-inetRouter:  -- Loader:            [0m
[1m==> Debian12-office2Server:  -- Memory:            1024M[0m
[1m==> Debian12-centralRouter:  -- Memory:            1024M[0m
[1m==> Debian12-inetRouter2:  -- Management MAC:    52:54:00:27:28:90[0m
[1m==> Debian12-centralRouter:  -- Management MAC:    52:54:00:27:28:84[0m
[1m==> Debian12-office1Server:  -- Nvram:             [0m
[1m==> Debian12-office1Server:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-office1Router:  -- Clock offset:      utc[0m
[1m==> Debian12-inetRouter:  -- Nvram:             [0m
[1m==> Debian12-office2Server:  -- Management MAC:    52:54:00:27:28:88[0m
[1m==> Debian12-inetRouter:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-inetRouter2:  -- Loader:            [0m
[1m==> Debian12-centralServer:  -- Cpus:              1[0m
[1m==> Debian12-centralRouter:  -- Loader:            [0m
[1m==> Debian12-office1Server:  -- Storage pool:      default[0m
[1m==> Debian12-office1Router:  -- Memory:            1024M[0m
[1m==> Debian12-office2Router:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-office2Router.img, virtio, 40G[0m
[1m==> Debian12-office2Server:  -- Loader:            [0m
[1m==> Debian12-inetRouter:  -- Storage pool:      default[0m
[1m==> Debian12-inetRouter:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-inetRouter.img, virtio, 40G[0m
[1m==> Debian12-centralServer:  -- Feature:           acpi[0m
[1m==> Debian12-centralRouter:  -- Nvram:             [0m
[1m==> Debian12-centralServer:  -- Feature:           apic[0m
[1m==> Debian12-office1Router:  -- Management MAC:    52:54:00:27:28:85[0m
[1m==> Debian12-office2Router:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-inetRouter2:  -- Nvram:             [0m
[1m==> Debian12-office2Server:  -- Nvram:             [0m
[1m==> Debian12-inetRouter:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-office1Server:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-office1Server.img, virtio, 40G[0m
[1m==> Debian12-centralServer:  -- Feature:           pae[0m
[1m==> Debian12-office1Server:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-office1Router:  -- Loader:            [0m
[1m==> Debian12-office2Router:  -- Kernel:            [0m
[1m==> Debian12-office1Router:  -- Nvram:             [0m
[1m==> Debian12-office2Router:  -- Initrd:            [0m
[1m==> Debian12-inetRouter:  -- Kernel:            [0m
[1m==> Debian12-centralRouter:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-centralServer:  -- Clock offset:      utc[0m
[1m==> Debian12-office1Server:  -- Kernel:            [0m
[1m==> Debian12-inetRouter2:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-inetRouter2:  -- Storage pool:      default[0m
[1m==> Debian12-office1Router:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-office2Router:  -- Graphics Type:     vnc[0m
[1m==> Debian12-inetRouter:  -- Initrd:            [0m
[1m==> Debian12-centralRouter:  -- Storage pool:      default[0m
[1m==> Debian12-centralServer:  -- Memory:            1024M[0m
[1m==> Debian12-centralServer:  -- Management MAC:    52:54:00:27:28:89[0m
[1m==> Debian12-office2Server:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-centralServer:  -- Loader:            [0m
[1m==> Debian12-office2Router:  -- Graphics Port:     -1[0m
[1m==> Debian12-office2Router:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-office1Server:  -- Initrd:            [0m
[1m==> Debian12-office1Server:  -- Graphics Type:     vnc[0m
[1m==> Debian12-inetRouter2:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-inetRouter2.img, virtio, 40G[0m
[1m==> Debian12-office1Router:  -- Storage pool:      default[0m
[1m==> Debian12-centralServer:  -- Nvram:             [0m
[1m==> Debian12-centralServer:  -- Base box:          /home/max/vagrant/images/debian12[0m
[1m==> Debian12-office2Server:  -- Storage pool:      default[0m
[1m==> Debian12-office2Router:  -- Graphics Password: Not defined[0m
[1m==> Debian12-office2Server:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-office2Server.img, virtio, 40G[0m
[1m==> Debian12-office1Server:  -- Graphics Port:     -1[0m
[1m==> Debian12-office1Server:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-office1Router:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-office1Router.img, virtio, 40G[0m
[1m==> Debian12-inetRouter:  -- Graphics Type:     vnc[0m
[1m==> Debian12-centralServer:  -- Storage pool:      default[0m
[1m==> Debian12-centralRouter:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-centralRouter.img, virtio, 40G[0m
[1m==> Debian12-inetRouter:  -- Graphics Port:     -1[0m
[1m==> Debian12-office2Server:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-office2Server:  -- Kernel:            [0m
[1m==> Debian12-office1Server:  -- Graphics Password: Not defined[0m
[1m==> Debian12-office2Server:  -- Initrd:            [0m
[1m==> Debian12-centralServer:  -- Image(vda):        /home/max/libvirt/images/default/vg3_Debian12-centralServer.img, virtio, 40G[0m
[1m==> Debian12-office2Server:  -- Graphics Type:     vnc[0m
[1m==> Debian12-centralRouter:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-centralRouter:  -- Kernel:            [0m
[1m==> Debian12-inetRouter:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-inetRouter:  -- Graphics Password: Not defined[0m
[1m==> Debian12-office1Server:  -- Video Type:        cirrus[0m
[1m==> Debian12-office1Server:  -- Video VRAM:        16384[0m
[1m==> Debian12-office2Server:  -- Graphics Port:     -1[0m
[1m==> Debian12-office2Server:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-centralRouter:  -- Initrd:            [0m
[1m==> Debian12-office1Router:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-centralServer:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-office1Router:  -- Kernel:            [0m
[1m==> Debian12-office2Router:  -- Video Type:        cirrus[0m
[1m==> Debian12-office2Router:  -- Video VRAM:        16384[0m
[1m==> Debian12-inetRouter2:  -- Disk driver opts:  cache='default'[0m
[1m==> Debian12-office2Server:  -- Graphics Password: Not defined[0m
[1m==> Debian12-office2Server:  -- Video Type:        cirrus[0m
[1m==> Debian12-inetRouter:  -- Video Type:        cirrus[0m
[1m==> Debian12-centralServer:  -- Kernel:            [0m
[1m==> Debian12-office1Router:  -- Initrd:            [0m
[1m==> Debian12-office1Server:  -- Video 3D accel:    false[0m
[1m==> Debian12-office2Router:  -- Video 3D accel:    false[0m
[1m==> Debian12-centralRouter:  -- Graphics Type:     vnc[0m
[1m==> Debian12-centralServer:  -- Initrd:            [0m
[1m==> Debian12-centralRouter:  -- Graphics Port:     -1[0m
[1m==> Debian12-inetRouter:  -- Video VRAM:        16384[0m
[1m==> Debian12-inetRouter:  -- Video 3D accel:    false[0m
[1m==> Debian12-office1Server:  -- Sound Type:        [0m
[1m==> Debian12-office1Server:  -- Keymap:            en-us[0m
[1m==> Debian12-office2Server:  -- Video VRAM:        16384[0m
[1m==> Debian12-inetRouter2:  -- Kernel:            [0m
[1m==> Debian12-centralRouter:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-centralRouter:  -- Graphics Password: Not defined[0m
[1m==> Debian12-centralRouter:  -- Video Type:        cirrus[0m
[1m==> Debian12-office2Router:  -- Sound Type:        [0m
[1m==> Debian12-inetRouter:  -- Sound Type:        [0m
[1m==> Debian12-office2Server:  -- Video 3D accel:    false[0m
[1m==> Debian12-office1Server:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-inetRouter2:  -- Initrd:            [0m
[1m==> Debian12-centralServer:  -- Graphics Type:     vnc[0m
[1m==> Debian12-centralServer:  -- Graphics Port:     -1[0m
[1m==> Debian12-centralRouter:  -- Video VRAM:        16384[0m
[1m==> Debian12-office2Router:  -- Keymap:            en-us[0m
[1m==> Debian12-inetRouter:  -- Keymap:            en-us[0m
[1m==> Debian12-office2Server:  -- Sound Type:        [0m
[1m==> Debian12-office1Router:  -- Graphics Type:     vnc[0m
[1m==> Debian12-office1Server:  -- TPM Path:          [0m
[1m==> Debian12-inetRouter2:  -- Graphics Type:     vnc[0m
[1m==> Debian12-centralServer:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-centralRouter:  -- Video 3D accel:    false[0m
[1m==> Debian12-office2Router:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-inetRouter:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-inetRouter:  -- TPM Path:          [0m
[1m==> Debian12-office1Router:  -- Graphics Port:     -1[0m
[1m==> Debian12-office1Server:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-inetRouter2:  -- Graphics Port:     -1[0m
[1m==> Debian12-inetRouter2:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-centralRouter:  -- Sound Type:        [0m
[1m==> Debian12-centralRouter:  -- Keymap:            en-us[0m
[1m==> Debian12-office2Server:  -- Keymap:            en-us[0m
[1m==> Debian12-inetRouter:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-office1Router:  -- Graphics IP:       127.0.0.1[0m
[1m==> Debian12-centralServer:  -- Graphics Password: Not defined[0m
[1m==> Debian12-inetRouter2:  -- Graphics Password: Not defined[0m
[1m==> Debian12-centralServer:  -- Video Type:        cirrus[0m
[1m==> Debian12-centralServer:  -- Video VRAM:        16384[0m
[1m==> Debian12-centralRouter:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-centralServer:  -- Video 3D accel:    false[0m
[1m==> Debian12-centralRouter:  -- TPM Path:          [0m
[1m==> Debian12-inetRouter2:  -- Video Type:        cirrus[0m
[1m==> Debian12-office2Server:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-office1Router:  -- Graphics Password: Not defined[0m
[1m==> Debian12-office2Server:  -- TPM Path:          [0m
[1m==> Debian12-centralServer:  -- Sound Type:        [0m
[1m==> Debian12-centralRouter:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-office2Server:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-office1Router:  -- Video Type:        cirrus[0m
[1m==> Debian12-office2Router:  -- TPM Path:          [0m
[1m==> Debian12-office2Router:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-inetRouter2:  -- Video VRAM:        16384[0m
[1;33m==> Debian12-inetRouter: You assigned a static IP ending in ".1" to this machine.
==> Debian12-inetRouter: This is very often used by the router and can cause the
==> Debian12-inetRouter: network to not work properly. If the network doesn't work
==> Debian12-inetRouter: properly, try changing this IP.[0m
[1m==> Debian12-inetRouter2:  -- Video 3D accel:    false[0m
[1m==> Debian12-inetRouter2:  -- Sound Type:        [0m
[1m==> Debian12-centralServer:  -- Keymap:            en-us[0m
[1m==> Debian12-centralServer:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-office1Router:  -- Video VRAM:        16384[0m
[1m==> Debian12-office1Router:  -- Video 3D accel:    false[0m
[1m==> Debian12-centralServer:  -- TPM Path:          [0m
[1m==> Debian12-inetRouter2:  -- Keymap:            en-us[0m
[1m==> Debian12-inetRouter2:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-office1Router:  -- Sound Type:        [0m
[1m==> Debian12-inetRouter2:  -- TPM Path:          [0m
[1m==> Debian12-office1Router:  -- Keymap:            en-us[0m
[1m==> Debian12-centralServer:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-inetRouter2:  -- INPUT:             type=mouse, bus=ps2[0m
[1m==> Debian12-office1Router:  -- TPM Backend:       passthrough[0m
[1m==> Debian12-office1Router:  -- TPM Path:          [0m
[1m==> Debian12-office1Router:  -- INPUT:             type=mouse, bus=ps2[0m
[1;33m==> Debian12-office1Router: You assigned a static IP ending in ".1" to this machine.
==> Debian12-office1Router: This is very often used by the router and can cause the
==> Debian12-office1Router: network to not work properly. If the network doesn't work
==> Debian12-office1Router: properly, try changing this IP.[0m
[1;33m==> Debian12-office2Router: You assigned a static IP ending in ".1" to this machine.
==> Debian12-office2Router: This is very often used by the router and can cause the
==> Debian12-office2Router: network to not work properly. If the network doesn't work
==> Debian12-office2Router: properly, try changing this IP.[0m
[1;33m==> Debian12-centralRouter: You assigned a static IP ending in ".1" to this machine.
==> Debian12-centralRouter: This is very often used by the router and can cause the
==> Debian12-centralRouter: network to not work properly. If the network doesn't work
==> Debian12-centralRouter: properly, try changing this IP.[0m
[1m==> Debian12-office1Server: Creating shared folders metadata...[0m
[1m==> Debian12-office1Server: Starting domain.[0m
[1m==> Debian12-inetRouter: Creating shared folders metadata...[0m
[1m==> Debian12-office1Server: Waiting for domain to get an IP address...[0m
[1m==> Debian12-office1Server: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-inetRouter: Starting domain.[0m
[1m==> Debian12-inetRouter: Waiting for domain to get an IP address...[0m
[1m==> Debian12-inetRouter: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-centralServer: Creating shared folders metadata...[0m
[1m==> Debian12-centralServer: Starting domain.[0m
[1m==> Debian12-centralServer: Waiting for domain to get an IP address...[0m
[0m    Debian12-inetRouter: SSH address: 192.168.121.10:22[0m
[0m    Debian12-office1Server: SSH address: 192.168.121.14:22[0m
[0m    Debian12-office1Server: SSH username: vagrant[0m
[1m==> Debian12-office2Server: Creating shared folders metadata...[0m
[0m    Debian12-office1Server: SSH auth method: private key[0m
[0m    Debian12-inetRouter: SSH username: vagrant[0m
[0m    Debian12-inetRouter: SSH auth method: private key[0m
[1m==> Debian12-centralServer: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-office2Server: Starting domain.[0m
[1m==> Debian12-office2Server: Waiting for domain to get an IP address...[0m
[1m==> Debian12-office2Server: Waiting for machine to boot. This may take a few minutes...[0m
[0m    Debian12-centralServer: SSH address: 192.168.121.16:22[0m
[0m    Debian12-office1Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-centralServer: SSH username: vagrant[0m
[0m    Debian12-centralServer: SSH auth method: private key[0m
[1m==> Debian12-office2Router: Creating shared folders metadata...[0m
[1m==> Debian12-office1Router: Creating shared folders metadata...[0m
[0m    Debian12-office2Server: SSH address: 192.168.121.15:22[0m
[0m    Debian12-office2Server: SSH username: vagrant[0m
[0m    Debian12-office2Server: SSH auth method: private key[0m
[1m==> Debian12-office2Router: Starting domain.[0m
[1m==> Debian12-office1Router: Starting domain.[0m
[1m==> Debian12-office1Router: Waiting for domain to get an IP address...[0m
[0m    Debian12-inetRouter: Warning: Host unreachable. Retrying...[0m
[1m==> Debian12-centralRouter: Creating shared folders metadata...[0m
[1m==> Debian12-centralRouter: Starting domain.[0m
[1m==> Debian12-office1Router: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-office2Router: Waiting for domain to get an IP address...[0m
[1m==> Debian12-centralRouter: Waiting for domain to get an IP address...[0m
[1m==> Debian12-inetRouter2: Creating shared folders metadata...[0m
[0m    Debian12-centralServer: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: Warning: Host unreachable. Retrying...[0m
[1m==> Debian12-centralRouter: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-office2Router: Waiting for machine to boot. This may take a few minutes...[0m
[1m==> Debian12-inetRouter2: Starting domain.[0m
[0m    Debian12-inetRouter: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office2Router: SSH address: 192.168.121.13:22[0m
[1m==> Debian12-inetRouter2: Waiting for domain to get an IP address...[0m
[0m    Debian12-office1Router: SSH address: 192.168.121.12:22[0m
[0m    Debian12-office1Router: SSH username: vagrant[0m
[1m==> Debian12-inetRouter2: Waiting for machine to boot. This may take a few minutes...[0m
[0m    Debian12-centralRouter: SSH address: 192.168.121.11:22[0m
[0m    Debian12-office2Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-centralRouter: SSH username: vagrant[0m
[0m    Debian12-centralRouter: SSH auth method: private key[0m
[0m    Debian12-office2Router: SSH username: vagrant[0m
[0m    Debian12-office1Router: SSH auth method: private key[0m
[0m    Debian12-inetRouter2: SSH address: 192.168.121.17:22[0m
[0m    Debian12-office2Router: SSH auth method: private key[0m
[0m    Debian12-inetRouter2: SSH username: vagrant[0m
[0m    Debian12-inetRouter2: SSH auth method: private key[0m
[0m    Debian12-centralServer: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Router: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-centralRouter: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office2Router: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-inetRouter: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-inetRouter2: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office2Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-centralServer: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-inetRouter: Warning: Connection refused. Retrying...[0m
[0m    Debian12-centralRouter: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Router: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office2Router: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-inetRouter2: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: Warning: Connection refused. Retrying...[0m
[0m    Debian12-centralServer: Warning: Connection refused. Retrying...[0m
[0m    Debian12-inetRouter: 
    Debian12-inetRouter: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-inetRouter: this with a newly generated keypair for better security.[0m
[0m    Debian12-office2Server: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: 
    Debian12-office1Server: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-office1Server: this with a newly generated keypair for better security.[0m
[0m    Debian12-inetRouter: 
    Debian12-inetRouter: Inserting generated public key within guest...[0m
[0m    Debian12-centralServer: 
    Debian12-centralServer: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-centralServer: this with a newly generated keypair for better security.[0m
[0m    Debian12-office2Server: 
    Debian12-office2Server: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-office2Server: this with a newly generated keypair for better security.[0m
[0m    Debian12-office1Server: 
    Debian12-office1Server: Inserting generated public key within guest...[0m
[0m    Debian12-office2Router: 
    Debian12-office2Router: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-office2Router: this with a newly generated keypair for better security.[0m
[0m    Debian12-centralServer: 
    Debian12-centralServer: Inserting generated public key within guest...[0m
[0m    Debian12-inetRouter: Removing insecure key from the guest if it's present...[0m
[0m    Debian12-office2Server: 
    Debian12-office2Server: Inserting generated public key within guest...[0m
[0m    Debian12-centralRouter: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office2Router: 
    Debian12-office2Router: Inserting generated public key within guest...[0m
[0m    Debian12-office1Router: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-office1Server: Removing insecure key from the guest if it's present...[0m
[0m    Debian12-office1Router: Warning: Connection refused. Retrying...[0m
[0m    Debian12-inetRouter2: Warning: Host unreachable. Retrying...[0m
[0m    Debian12-centralServer: Removing insecure key from the guest if it's present...[0m
[0m    Debian12-office2Server: Removing insecure key from the guest if it's present...[0m
[0m    Debian12-inetRouter: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0m    Debian12-office2Router: Removing insecure key from the guest if it's present...[0m
[0m    Debian12-office1Server: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0m    Debian12-office2Server: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0m    Debian12-centralServer: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[1m==> Debian12-inetRouter: Machine booted and ready![0m
[0m    Debian12-office1Router: 
    Debian12-office1Router: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-office1Router: this with a newly generated keypair for better security.[0m
[0m    Debian12-office2Router: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[1m==> Debian12-office2Server: Machine booted and ready![0m
[0m    Debian12-office1Router: 
    Debian12-office1Router: Inserting generated public key within guest...[0m
[1m==> Debian12-office1Server: Machine booted and ready![0m
[1m==> Debian12-centralServer: Machine booted and ready![0m
[1m==> Debian12-inetRouter: Configuring and enabling network interfaces...[0m
[1m==> Debian12-office2Router: Machine booted and ready![0m
[1m==> Debian12-office2Server: Configuring and enabling network interfaces...[0m
[0m    Debian12-office1Router: Removing insecure key from the guest if it's present...[0m
[1m==> Debian12-office1Server: Configuring and enabling network interfaces...[0m
[1m==> Debian12-centralServer: Configuring and enabling network interfaces...[0m
[1m==> Debian12-office2Router: Configuring and enabling network interfaces...[0m
[0m    Debian12-office1Router: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0m    Debian12-centralRouter: Warning: Host unreachable. Retrying...[0m
[1m==> Debian12-office1Router: Machine booted and ready![0m
[0m    Debian12-centralRouter: Warning: Connection refused. Retrying...[0m
[1m==> Debian12-inetRouter: Running provisioner: shell...[0m
[1m==> Debian12-office2Server: Running provisioner: shell...[0m
[0m    Debian12-inetRouter2: Warning: Connection refused. Retrying...[0m
[1m==> Debian12-office1Router: Configuring and enabling network interfaces...[0m
[0m    Debian12-inetRouter: Running: inline script[0m
[1m==> Debian12-centralServer: Running provisioner: shell...[0m
[1m==> Debian12-office1Server: Running provisioner: shell...[0m
[0m    Debian12-office2Server: Running: inline script[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;32m    Debian12-inetRouter: Set Hostname[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-office2Server: Set Hostname[0m
[0m    Debian12-centralRouter: 
    Debian12-centralRouter: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-centralRouter: this with a newly generated keypair for better security.[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-office2Server: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-office2Server: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-office2Server: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-office2Server: *************************************************************[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;31m    Debian12-office2Server: [0m
[1m==> Debian12-office2Router: Running provisioner: shell...[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;31m    Debian12-office2Server: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office2Server: [0m
[0;32m    Debian12-inetRouter: Изменим ttl для работы через раздающий телефон[0m
[0m    Debian12-centralServer: Running: inline script[0m
[0m    Debian12-inetRouter2: 
    Debian12-inetRouter2: Vagrant insecure key detected. Vagrant will automatically replace
    Debian12-inetRouter2: this with a newly generated keypair for better security.[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;32m    Debian12-inetRouter: net.ipv4.ip_default_ttl = 66[0m
[0m    Debian12-office1Server: Running: inline script[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;32m    Debian12-inetRouter: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-inetRouter: *************************************************************[0m
[0;31m    Debian12-inetRouter: [0m
[0;31m    Debian12-inetRouter: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-inetRouter: [0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0;32m    Debian12-inetRouter: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-inetRouter: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-centralServer: Set Hostname[0m
[0;32m    Debian12-inetRouter: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;32m    Debian12-office2Server: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-office2Server: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-office2Server: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office1Server: Set Hostname[0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0;32m    Debian12-centralServer: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0;32m    Debian12-centralServer: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0;32m    Debian12-centralServer: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-centralServer: *************************************************************[0m
[0m    Debian12-office2Router: Running: inline script[0m
[0;31m    Debian12-centralServer: [0m
[0;31m    Debian12-centralServer: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-centralServer: [0m
[0m    Debian12-centralRouter: 
    Debian12-centralRouter: Inserting generated public key within guest...[0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office1Server: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office1Server: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office1Server: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-office2Router: Set Hostname[0m
[0m    Debian12-inetRouter2: 
    Debian12-inetRouter2: Inserting generated public key within guest...[0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;32m    Debian12-office1Server: *************************************************************[0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;32m    Debian12-office2Router: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;31m    Debian12-office1Server: [0m
[0;31m    Debian12-office1Server: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;32m    Debian12-office2Router: net.ipv4.ip_default_ttl = 66[0m
[0;31m    Debian12-office1Server: [0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;32m    Debian12-office2Router: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-office2Router: *************************************************************[0m
[0;32m    Debian12-centralServer: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-centralServer: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-centralServer: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;31m    Debian12-office2Router: [0m
[0;31m    Debian12-office2Router: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office2Router: [0m
[0;32m    Debian12-office1Server: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-office1Server: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-office1Server: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0m    Debian12-centralRouter: Removing insecure key from the guest if it's present...[0m
[0;32m    Debian12-office2Router: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-office2Router: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-office2Router: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;32m    Debian12-inetRouter: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0m    Debian12-inetRouter2: Removing insecure key from the guest if it's present...[0m
[0;32m    Debian12-office2Server: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-inetRouter: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-office2Server: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-inetRouter: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-inetRouter: Получено 526 kB за 3с (194 kB/s)[0m
[1m==> Debian12-office1Router: Running provisioner: shell...[0m
[0;32m    Debian12-office2Server: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0m    Debian12-centralRouter: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0;32m    Debian12-centralServer: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-office2Server: Получено 526 kB за 3с (152 kB/s)[0m
[0;32m    Debian12-centralServer: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0m    Debian12-inetRouter2: Key inserted! Disconnecting and reconnecting using new SSH key...[0m
[0;32m    Debian12-centralServer: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-centralServer: Получено 526 kB за 3с (175 kB/s)[0m
[0;32m    Debian12-office2Router: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0m    Debian12-office1Router: Running: inline script[0m
[0;32m    Debian12-office2Router: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;32m    Debian12-office1Router: Set Hostname[0m
[0;32m    Debian12-office2Router: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;32m    Debian12-office1Router: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;32m    Debian12-office1Router: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;32m    Debian12-office1Router: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-office1Router: *************************************************************[0m
[0;31m    Debian12-office1Router: [0m
[0;31m    Debian12-office1Router: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office1Router: [0m
[0;32m    Debian12-office2Router: Получено 526 kB за 3с (180 kB/s)[0m
[0;32m    Debian12-office1Router: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[1m==> Debian12-inetRouter2: Machine booted and ready![0m
[1m==> Debian12-centralRouter: Machine booted and ready![0m
[0;32m    Debian12-office1Router: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-office1Router: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[1m==> Debian12-centralRouter: Configuring and enabling network interfaces...[0m
[1m==> Debian12-inetRouter2: Configuring and enabling network interfaces...[0m
[0;32m    Debian12-office1Router: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-office1Router: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-office1Router: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-office1Router: Получено 526 kB за 2с (216 kB/s)[0m
[1m==> Debian12-inetRouter2: Running provisioner: shell...[0m
[1m==> Debian12-centralRouter: Running provisioner: shell...[0m
[0;32m    Debian12-inetRouter: Чтение списков пакетов…[0m
[0m    Debian12-inetRouter2: Running: inline script[0m
[0m    Debian12-centralRouter: Running: inline script[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-inetRouter2: Set Hostname[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;32m    Debian12-centralRouter: Set Hostname[0m
[0;32m    Debian12-centralServer: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-office2Server: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter2: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-inetRouter2: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-inetRouter2: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-inetRouter2: *************************************************************[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;32m    Debian12-centralRouter: Изменим ttl для работы через раздающий телефон[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;32m    Debian12-centralRouter: net.ipv4.ip_default_ttl = 66[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;32m    Debian12-centralRouter: Если ранее не были установлены, то установим необходимые  пакеты[0m
[0;32m    Debian12-centralRouter: *************************************************************[0m
[0;31m    Debian12-inetRouter2: [0m
[0;31m    Debian12-inetRouter2: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-inetRouter2: [0m
[0;31m    Debian12-centralRouter: [0m
[0;31m    Debian12-centralRouter: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-centralRouter: [0m
[0;32m    Debian12-centralServer: Построение дерева зависимостей…[0m
[0;32m    Debian12-centralServer: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter: Построение дерева зависимостей…[0m
[0;32m    Debian12-inetRouter: Чтение информации о состоянии…[0m
[0;32m    Debian12-centralServer: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;32m    Debian12-inetRouter: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;31m    Debian12-centralServer: [0m
[0;31m    Debian12-centralServer: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-centralServer: [0m
[0;31m    Debian12-inetRouter: [0m
[0;32m    Debian12-office2Server: Построение дерева зависимостей…[0m
[0;31m    Debian12-inetRouter: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;32m    Debian12-office2Server: Чтение информации о состоянии…[0m
[0;31m    Debian12-inetRouter: [0m
[0;32m    Debian12-office2Server: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;32m    Debian12-inetRouter2: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-inetRouter2: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-inetRouter2: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;31m    Debian12-office2Server: [0m
[0;31m    Debian12-office2Server: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office2Server: [0m
[0;32m    Debian12-centralServer: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter: Чтение списков пакетов…[0m
[0;32m    Debian12-centralRouter: Сущ:1 http://ftp.ru.debian.org/debian bookworm InRelease[0m
[0;32m    Debian12-centralRouter: Пол:2 http://ftp.ru.debian.org/debian bookworm-updates InRelease [55,4 kB][0m
[0;32m    Debian12-centralRouter: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;32m    Debian12-office2Server: Чтение списков пакетов…[0m
[0;32m    Debian12-office2Server: Построение дерева зависимостей…[0m
[0;32m    Debian12-office2Server: Чтение информации о состоянии…[0m
[0;32m    Debian12-centralServer: Построение дерева зависимостей…[0m
[0;32m    Debian12-centralServer: Чтение информации о состоянии…[0m
[0;32m    Debian12-office2Router: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter: Построение дерева зависимостей…[0m
[0;32m    Debian12-inetRouter: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter2: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-inetRouter2: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-inetRouter: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-inetRouter: Будут установлены следующие дополнительные пакеты:[0m
[0;32m    Debian12-inetRouter:   libip6tc2 libnetfilter-conntrack3 libnfnetlink0 netfilter-persistent[0m
[0;32m    Debian12-inetRouter: Предлагаемые пакеты:[0m
[0;32m    Debian12-inetRouter:   firewalld[0m
[0;32m    Debian12-centralServer: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-centralServer: Предлагаемые пакеты:[0m
[0;32m    Debian12-centralServer:   fcgiwrap nginx-doc ssl-cert[0m
[0;32m    Debian12-inetRouter: Следующие НОВЫЕ пакеты будут установлены:[0m
[0;32m    Debian12-inetRouter:   iptables iptables-persistent libip6tc2 libnetfilter-conntrack3 libnfnetlink0[0m
[0;32m    Debian12-inetRouter2: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-inetRouter:   netfilter-persistent[0m
[0;32m    Debian12-office2Server: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-office2Server: Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-centralServer: Следующие НОВЫЕ пакеты будут установлены:[0m
[0;32m    Debian12-centralServer:   nginx nginx-common[0m
[0;32m    Debian12-centralRouter: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-office2Router: Построение дерева зависимостей…[0m
[0;32m    Debian12-office2Router: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter: Обновлено 0 пакетов, установлено 6 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-inetRouter: Необходимо скачать 452 kB архивов.[0m
[0;32m    Debian12-inetRouter: После данной операции объём занятого дискового пространства возрастёт на 2 817 kB.[0m
[0;32m    Debian12-inetRouter: Пол:1 http://ftp.ru.debian.org/debian bookworm/main amd64 libip6tc2 amd64 1.8.9-2 [19,4 kB][0m
[0;32m    Debian12-office2Router: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;32m    Debian12-centralServer: Обновлено 0 пакетов, установлено 2 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-centralServer: Необходимо скачать 640 kB архивов.[0m
[0;32m    Debian12-centralServer: После данной операции объём занятого дискового пространства возрастёт на 1 696 kB.[0m
[0;31m    Debian12-office2Router: [0m
[0;32m    Debian12-centralServer: Пол:1 http://ftp.ru.debian.org/debian bookworm/main amd64 nginx-common all 1.22.1-9 [112 kB][0m
[0;31m    Debian12-office2Router: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office2Router: [0m
[0;32m    Debian12-inetRouter: Пол:2 http://ftp.ru.debian.org/debian bookworm/main amd64 libnfnetlink0 amd64 1.0.2-2 [15,1 kB][0m
[0;32m    Debian12-inetRouter: Пол:3 http://ftp.ru.debian.org/debian bookworm/main amd64 libnetfilter-conntrack3 amd64 1.0.9-3 [40,7 kB][0m
[0;32m    Debian12-inetRouter: Пол:4 http://ftp.ru.debian.org/debian bookworm/main amd64 iptables amd64 1.8.9-2 [360 kB][0m
[0;32m    Debian12-centralRouter: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-office2Router: Чтение списков пакетов…[0m
[0;32m    Debian12-centralServer: Пол:2 http://ftp.ru.debian.org/debian bookworm/main amd64 nginx amd64 1.22.1-9 [527 kB][0m
[0;32m    Debian12-inetRouter2: Получено 526 kB за 3с (173 kB/s)[0m
[0;32m    Debian12-inetRouter: Пол:5 http://ftp.ru.debian.org/debian bookworm/main amd64 netfilter-persistent all 1.0.20 [7 384 B][0m
[0;32m    Debian12-inetRouter: Пол:6 http://ftp.ru.debian.org/debian bookworm/main amd64 iptables-persistent all 1.0.20 [9 000 B][0m
[0;32m    Debian12-centralRouter: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-centralRouter: Получено 526 kB за 4с (147 kB/s)[0m
[0;32m    Debian12-office2Router: Построение дерева зависимостей…[0m
[0;32m    Debian12-office2Router: Чтение информации о состоянии…[0m
[0;32m    Debian12-office1Router: Чтение списков пакетов…[0m
[0;32m    Debian12-office2Router: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-office2Router: Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-office2Router: net.ipv4.conf.all.forwarding = 1[0m
[0;32m    Debian12-office1Router: Построение дерева зависимостей…[0m
[0;32m    Debian12-office1Router: Чтение информации о состоянии…[0m
[0;32m    Debian12-office1Router: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;31m    Debian12-office1Router: [0m
[0;31m    Debian12-office1Router: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office1Router: [0m
[0;32m    Debian12-office1Router: Чтение списков пакетов…[0m
[0;32m    Debian12-office1Router: Построение дерева зависимостей…[0m
[0;32m    Debian12-office1Router: Чтение информации о состоянии…[0m
[0;32m    Debian12-centralServer: Предварительная настройка пакетов …[0m
[0;32m    Debian12-office1Router: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-office1Router: Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-office1Router: net.ipv4.conf.all.forwarding = 1[0m
[0;32m    Debian12-inetRouter: Предварительная настройка пакетов …[0m
[0;32m    Debian12-centralServer: Получено 640 kB за 1с (787 kB/s)[0m
[0;32m    Debian12-inetRouter: Получено 452 kB за 1с (816 kB/s)[0m
[0;32m    Debian12-centralServer: Выбор ранее не выбранного пакета nginx-common.[0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета libip6tc2:amd64.[0m
[0;32m    Debian12-centralServer: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 34810 файлов и каталогов.)[0m
[0;32m    Debian12-centralServer: Подготовка к распаковке …/nginx-common_1.22.1-9_all.deb …[0m
[0;32m    Debian12-centralServer: Распаковывается nginx-common (1.22.1-9) …[0m
[0;32m    Debian12-inetRouter: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 34810 файлов и каталогов.)[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/libip6tc2_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter: Распаковывается libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-centralServer: Выбор ранее не выбранного пакета nginx.[0m
[0;32m    Debian12-centralServer: Подготовка к распаковке …/nginx_1.22.1-9_amd64.deb …[0m
[0;32m    Debian12-centralServer: Распаковывается nginx (1.22.1-9) …[0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета libnfnetlink0:amd64.[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/libnfnetlink0_1.0.2-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter: Распаковывается libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-centralRouter: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета libnetfilter-conntrack3:amd64.[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/libnetfilter-conntrack3_1.0.9-3_amd64.deb …[0m
[0;32m    Debian12-inetRouter: Распаковывается libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-centralServer: Настраивается пакет nginx-common (1.22.1-9) …[0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета iptables.[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/iptables_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter: Распаковывается iptables (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: Чтение списков пакетов…[0m
[0;32m    Debian12-centralRouter: Построение дерева зависимостей…[0m
[0;32m    Debian12-centralRouter: Чтение информации о состоянии…[0m
[0;32m    Debian12-centralRouter: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;31m    Debian12-centralRouter: [0m
[0;31m    Debian12-centralRouter: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-centralRouter: [0m
[0;32m    Debian12-centralRouter: Чтение списков пакетов…[0m
[0;32m    Debian12-inetRouter2: Построение дерева зависимостей…[0m
[0;32m    Debian12-inetRouter2: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter2: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;31m    Debian12-inetRouter2: [0m
[0;31m    Debian12-inetRouter2: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-inetRouter2: [0m
[0;32m    Debian12-inetRouter2: Чтение списков пакетов…[0m
[0;32m    Debian12-centralRouter: Построение дерева зависимостей…[0m
[0;32m    Debian12-centralRouter: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета netfilter-persistent.[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/netfilter-persistent_1.0.20_all.deb …[0m
[0;32m    Debian12-inetRouter: Распаковывается netfilter-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter: Настраивается пакет libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: Построение дерева зависимостей…[0m
[0;32m    Debian12-inetRouter2: Чтение информации о состоянии…[0m
[0;32m    Debian12-inetRouter: Настраивается пакет libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-inetRouter: Настраивается пакет libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-inetRouter: Настраивается пакет iptables (1.8.9-2) …[0m
[0;32m    Debian12-centralRouter: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-centralRouter: Будут установлены следующие дополнительные пакеты:[0m
[0;32m    Debian12-centralRouter:   libblas3 libip6tc2 liblinear4 liblua5.3-0 libnetfilter-conntrack3[0m
[0;32m    Debian12-centralRouter:   libnfnetlink0 libpcap0.8 libpcre3 lua-lpeg nmap-common[0m
[0;32m    Debian12-centralRouter: Предлагаемые пакеты:[0m
[0;32m    Debian12-centralRouter:   firewalld liblinear-tools liblinear-dev ncat ndiff zenmap[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/iptables-legacy для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: Следующие НОВЫЕ пакеты будут установлены:[0m
[0;32m    Debian12-centralRouter:   iptables libblas3 libip6tc2 liblinear4 liblua5.3-0 libnetfilter-conntrack3[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/ip6tables-legacy для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter:   libnfnetlink0 libpcap0.8 libpcre3 lua-lpeg nmap nmap-common[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/iptables-nft для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/ip6tables-nft для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-inetRouter2: Будут установлены следующие дополнительные пакеты:[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/arptables-nft для предоставления /usr/sbin/arptables (arptables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2:   libip6tc2 libnetfilter-conntrack3 libnfnetlink0 netfilter-persistent[0m
[0;32m    Debian12-inetRouter2: Предлагаемые пакеты:[0m
[0;32m    Debian12-inetRouter2:   firewalld[0m
[0;32m    Debian12-inetRouter: update-alternatives: используется /usr/sbin/ebtables-nft для предоставления /usr/sbin/ebtables (ebtables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: Следующие НОВЫЕ пакеты будут установлены:[0m
[0;32m    Debian12-inetRouter2:   iptables iptables-persistent libip6tc2 libnetfilter-conntrack3 libnfnetlink0[0m
[0;32m    Debian12-inetRouter2:   netfilter-persistent[0m
[0;32m    Debian12-centralRouter: Обновлено 0 пакетов, установлено 12 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-centralRouter: Необходимо скачать 7 332 kB архивов.[0m
[0;32m    Debian12-centralRouter: После данной операции объём занятого дискового пространства возрастёт на 31,4 MB.[0m
[0;32m    Debian12-centralRouter: Пол:1 http://ftp.ru.debian.org/debian bookworm/main amd64 libip6tc2 amd64 1.8.9-2 [19,4 kB][0m
[0;32m    Debian12-centralRouter: Пол:2 http://ftp.ru.debian.org/debian bookworm/main amd64 libnfnetlink0 amd64 1.0.2-2 [15,1 kB][0m
[0;32m    Debian12-centralRouter: Пол:3 http://ftp.ru.debian.org/debian bookworm/main amd64 libnetfilter-conntrack3 amd64 1.0.9-3 [40,7 kB][0m
[0;32m    Debian12-inetRouter2: Обновлено 0 пакетов, установлено 6 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-inetRouter2: Необходимо скачать 452 kB архивов.[0m
[0;32m    Debian12-inetRouter2: После данной операции объём занятого дискового пространства возрастёт на 2 817 kB.[0m
[0;32m    Debian12-inetRouter2: Пол:1 http://ftp.ru.debian.org/debian bookworm/main amd64 libip6tc2 amd64 1.8.9-2 [19,4 kB][0m
[0;32m    Debian12-inetRouter: Выбор ранее не выбранного пакета iptables-persistent.[0m
[0;32m    Debian12-centralRouter: Пол:4 http://ftp.ru.debian.org/debian bookworm/main amd64 iptables amd64 1.8.9-2 [360 kB][0m
[0;32m    Debian12-inetRouter2: Пол:2 http://ftp.ru.debian.org/debian bookworm/main amd64 libnfnetlink0 amd64 1.0.2-2 [15,1 kB][0m
[0;32m    Debian12-inetRouter2: Пол:3 http://ftp.ru.debian.org/debian bookworm/main amd64 libnetfilter-conntrack3 amd64 1.0.9-3 [40,7 kB][0m
[0;32m    Debian12-inetRouter: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 35042 файла и каталога.)[0m
[0;32m    Debian12-inetRouter: Подготовка к распаковке …/iptables-persistent_1.0.20_all.deb …[0m
[0;32m    Debian12-inetRouter2: Пол:4 http://ftp.ru.debian.org/debian bookworm/main amd64 iptables amd64 1.8.9-2 [360 kB][0m
[0;32m    Debian12-centralServer: Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /lib/systemd/system/nginx.service.[0m
[0;32m    Debian12-inetRouter2: Пол:5 http://ftp.ru.debian.org/debian bookworm/main amd64 netfilter-persistent all 1.0.20 [7 384 B][0m
[0;32m    Debian12-inetRouter2: Пол:6 http://ftp.ru.debian.org/debian bookworm/main amd64 iptables-persistent all 1.0.20 [9 000 B][0m
[0;32m    Debian12-centralRouter: Пол:5 http://ftp.ru.debian.org/debian bookworm/main amd64 libblas3 amd64 3.11.0-2 [149 kB][0m
[0;32m    Debian12-centralRouter: Пол:6 http://ftp.ru.debian.org/debian bookworm/main amd64 liblinear4 amd64 2.3.0+dfsg-5 [43,6 kB][0m
[0;32m    Debian12-centralRouter: Пол:7 http://ftp.ru.debian.org/debian bookworm/main amd64 liblua5.3-0 amd64 5.3.6-2 [123 kB][0m
[0;32m    Debian12-centralRouter: Пол:8 http://ftp.ru.debian.org/debian bookworm/main amd64 libpcap0.8 amd64 1.10.3-1 [157 kB][0m
[0;32m    Debian12-centralRouter: Пол:9 http://ftp.ru.debian.org/debian bookworm/main amd64 libpcre3 amd64 2:8.39-15 [341 kB][0m
[0;32m    Debian12-centralRouter: Пол:10 http://ftp.ru.debian.org/debian bookworm/main amd64 lua-lpeg amd64 1.0.2-2 [37,7 kB][0m
[0;32m    Debian12-centralRouter: Пол:11 http://ftp.ru.debian.org/debian bookworm/main amd64 nmap-common all 7.93+dfsg1-1 [4 148 kB][0m
[0;32m    Debian12-inetRouter: Распаковывается iptables-persistent (1.0.20) …[0m
[0;32m    Debian12-centralServer: Настраивается пакет nginx (1.22.1-9) …[0m
[0;32m    Debian12-inetRouter: Настраивается пакет netfilter-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter2: Предварительная настройка пакетов …[0m
[0;32m    Debian12-centralServer: Upgrading binary: nginx.[0m
[0;32m    Debian12-inetRouter: Created symlink /etc/systemd/system/iptables.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-inetRouter: Created symlink /etc/systemd/system/ip6tables.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-inetRouter: Created symlink /etc/systemd/system/multi-user.target.wants/netfilter-persistent.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-centralServer: Обрабатываются триггеры для man-db (2.11.2-2) …[0m
[0;32m    Debian12-inetRouter2: Получено 452 kB за 1с (561 kB/s)[0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета libip6tc2:amd64.[0m
[0;32m    Debian12-inetRouter: Настраивается пакет iptables-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter2: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 34810 файлов и каталогов.)[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/libip6tc2_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-centralRouter: Пол:12 http://ftp.ru.debian.org/debian bookworm/main amd64 nmap amd64 7.93+dfsg1-1 [1 897 kB][0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета libnfnetlink0:amd64.[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/libnfnetlink0_1.0.2-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета libnetfilter-conntrack3:amd64.[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/libnetfilter-conntrack3_1.0.9-3_amd64.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета iptables.[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/iptables_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается iptables (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета netfilter-persistent.[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/netfilter-persistent_1.0.20_all.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается netfilter-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет iptables (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/iptables-legacy для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/ip6tables-legacy для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/iptables-nft для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/ip6tables-nft для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/arptables-nft для предоставления /usr/sbin/arptables (arptables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter2: update-alternatives: используется /usr/sbin/ebtables-nft для предоставления /usr/sbin/ebtables (ebtables) в автоматическом режиме[0m
[0;32m    Debian12-inetRouter: Обрабатываются триггеры для man-db (2.11.2-2) …[0m
[0;32m    Debian12-inetRouter2: Выбор ранее не выбранного пакета iptables-persistent.[0m
[0;32m    Debian12-inetRouter2: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 35042 файла и каталога.)[0m
[0;32m    Debian12-inetRouter2: Подготовка к распаковке …/iptables-persistent_1.0.20_all.deb …[0m
[0;32m    Debian12-inetRouter2: Распаковывается iptables-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет netfilter-persistent (1.0.20) …[0m
[0;32m    Debian12-inetRouter2: Created symlink /etc/systemd/system/iptables.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-inetRouter2: Created symlink /etc/systemd/system/ip6tables.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-inetRouter2: Created symlink /etc/systemd/system/multi-user.target.wants/netfilter-persistent.service → /lib/systemd/system/netfilter-persistent.service.[0m
[0;32m    Debian12-inetRouter: Обрабатываются триггеры для libc-bin (2.36-9+deb12u8) …[0m
[0;32m    Debian12-centralRouter: Получено 7 332 kB за 7с (1 079 kB/s)[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libip6tc2:amd64.[0m
[0;32m    Debian12-centralRouter: (Чтение базы данных … (Чтение базы данных … 5%(Чтение базы данных … 10%(Чтение базы данных … 15%(Чтение базы данных … 20%(Чтение базы данных … 25%(Чтение базы данных … 30%(Чтение базы данных … 35%(Чтение базы данных … 40%(Чтение базы данных … 45%(Чтение базы данных … 50%(Чтение базы данных … 55%(Чтение базы данных … 60%(Чтение базы данных … 65%(Чтение базы данных … 70%(Чтение базы данных … 75%(Чтение базы данных … 80%(Чтение базы данных … 85%(Чтение базы данных … 90%(Чтение базы данных … 95%(Чтение базы данных … 100%(Чтение базы данных … на данный момент установлено 34810 файлов и каталогов.)[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/00-libip6tc2_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: Настраивается пакет iptables-persistent (1.0.20) …[0m
[0;31m    Debian12-inetRouter: run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save[0m
[0;31m    Debian12-inetRouter: run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save[0m
[0;32m    Debian12-inetRouter: net.ipv4.conf.all.forwarding = 1[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libnfnetlink0:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/01-libnfnetlink0_1.0.2-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libnetfilter-conntrack3:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/02-libnetfilter-conntrack3_1.0.9-3_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета iptables.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/03-iptables_1.8.9-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается iptables (1.8.9-2) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libblas3:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/04-libblas3_3.11.0-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libblas3:amd64 (3.11.0-2) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета liblinear4:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/05-liblinear4_2.3.0+dfsg-5_amd64.deb …[0m
[0;32m    Debian12-office1Server: Игн:3 http://security.debian.org/debian-security bookworm-security InRelease[0m
[0;32m    Debian12-centralRouter: Распаковывается liblinear4:amd64 (2.3.0+dfsg-5) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета liblua5.3-0:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/06-liblua5.3-0_5.3.6-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается liblua5.3-0:amd64 (5.3.6-2) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libpcap0.8:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/07-libpcap0.8_1.10.3-1_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libpcap0.8:amd64 (1.10.3-1) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета libpcre3:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/08-libpcre3_2%3a8.39-15_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается libpcre3:amd64 (2:8.39-15) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета lua-lpeg:amd64.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/09-lua-lpeg_1.0.2-2_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается lua-lpeg:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета nmap-common.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/10-nmap-common_7.93+dfsg1-1_all.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается nmap-common (7.93+dfsg1-1) …[0m
[0;32m    Debian12-office1Server: Пол:3 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB][0m
[0;32m    Debian12-inetRouter2: Обрабатываются триггеры для man-db (2.11.2-2) …[0m
[0;32m    Debian12-office1Server: Пол:4 http://security.debian.org/debian-security bookworm-security/main Sources [120 kB][0m
[0;32m    Debian12-office1Server: Пол:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [188 kB][0m
[0;32m    Debian12-office1Server: Пол:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [114 kB][0m
[0;32m    Debian12-office1Server: Получено 526 kB за 32с (16,4 kB/s)[0m
[0;32m    Debian12-centralRouter: Выбор ранее не выбранного пакета nmap.[0m
[0;32m    Debian12-centralRouter: Подготовка к распаковке …/11-nmap_7.93+dfsg1-1_amd64.deb …[0m
[0;32m    Debian12-centralRouter: Распаковывается nmap (7.93+dfsg1-1) …[0m
[0;32m    Debian12-inetRouter2: Обрабатываются триггеры для libc-bin (2.36-9+deb12u8) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет lua-lpeg:amd64 (1.0.2-2) …[0m
[0;31m    Debian12-inetRouter2: run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save[0m
[0;31m    Debian12-inetRouter2: run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libip6tc2:amd64 (1.8.9-2) …[0m
[0;32m    Debian12-inetRouter2: net.ipv4.conf.all.forwarding = 1[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libpcre3:amd64 (2:8.39-15) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libblas3:amd64 (3.11.0-2) …[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 для предоставления /usr/lib/x86_64-linux-gnu/libblas.so.3 (libblas.so.3-x86_64-linux-gnu) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libpcap0.8:amd64 (1.10.3-1) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет nmap-common (7.93+dfsg1-1) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libnfnetlink0:amd64 (1.0.2-2) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет liblua5.3-0:amd64 (5.3.6-2) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет liblinear4:amd64 (2.3.0+dfsg-5) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет libnetfilter-conntrack3:amd64 (1.0.9-3) …[0m
[0;32m    Debian12-centralRouter: Настраивается пакет iptables (1.8.9-2) …[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/iptables-legacy для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/ip6tables-legacy для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/iptables-nft для предоставления /usr/sbin/iptables (iptables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/ip6tables-nft для предоставления /usr/sbin/ip6tables (ip6tables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/arptables-nft для предоставления /usr/sbin/arptables (arptables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: update-alternatives: используется /usr/sbin/ebtables-nft для предоставления /usr/sbin/ebtables (ebtables) в автоматическом режиме[0m
[0;32m    Debian12-centralRouter: Настраивается пакет nmap (7.93+dfsg1-1) …[0m
[0;32m    Debian12-centralRouter: Обрабатываются триггеры для man-db (2.11.2-2) …[0m
[0;32m    Debian12-office1Server: Чтение списков пакетов…[0m
[0;32m    Debian12-office1Server: Построение дерева зависимостей…[0m
[0;32m    Debian12-office1Server: Чтение информации о состоянии…[0m
[0;32m    Debian12-office1Server: Может быть обновлён 1 пакет. Запустите «apt list --upgradable» для показа.[0m
[0;31m    Debian12-office1Server: [0m
[0;31m    Debian12-office1Server: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.[0m
[0;31m    Debian12-office1Server: [0m
[0;32m    Debian12-office1Server: Чтение списков пакетов…[0m
[0;32m    Debian12-office1Server: Построение дерева зависимостей…[0m
[0;32m    Debian12-office1Server: Чтение информации о состоянии…[0m
[0;32m    Debian12-office1Server: Уже установлен пакет traceroute самой новой версии (1:2.1.2-1).[0m
[0;32m    Debian12-office1Server: Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.[0m
[0;32m    Debian12-centralRouter: Обрабатываются триггеры для libc-bin (2.36-9+deb12u8) …[0m
[0;32m    Debian12-centralRouter: net.ipv4.conf.all.forwarding = 1[0m
7]2;max@localhost.localdomain:~/vagrant/vg3]1;localhost.localdomain8max@localhost:~/vagrant/vg3> vagrant ssh Debian12-centralRouter 
[1;33m==> Debian12-centralRouter: You assigned a static IP ending in ".1" to this machine.
==> Debian12-centralRouter: This is very often used by the router and can cause the
==> Debian12-centralRouter: network to not work properly. If the network doesn't work
==> Debian12-centralRouter: properly, try changing this IP.[0m
Linux centralrouter 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Sep 30 11:45:32 2024
[?2004h]0;vagrant@centralrouter: ~[01;32mvagrant@centralrouter[00m:[01;34m~[00m$ ssh 192.168.1.1
[?2004l
[?2004h]0;vagrant@centralrouter: ~[01;32mvagrant@centralrouter[00m:[01;34m~[00m$ ./knock.sh 192.168.1.1 111 222 [K[K[K[K[K1 2222 333 [K3 44444[K && ssh 192.168.1.1
[?2004lStarting Nmap 7.93 ( https://nmap.org ) at 2024-10-12 22:46 MSK
Warning: 192.168.1.1 giving up on port because retransmission cap hit (0).
Nmap scan report for 192.168.1.1
Host is up.

PORT     STATE    SERVICE
1111/tcp filtered lmsocialserver

Nmap done: 1 IP address (1 host up) scanned in 1.09 seconds
Starting Nmap 7.93 ( https://nmap.org ) at 2024-10-12 22:46 MSK
Warning: 192.168.1.1 giving up on port because retransmission cap hit (0).
Nmap scan report for 192.168.1.1
Host is up.

PORT     STATE    SERVICE
2222/tcp filtered EtherNetIP-1

Nmap done: 1 IP address (1 host up) scanned in 1.07 seconds
Starting Nmap 7.93 ( https://nmap.org ) at 2024-10-12 22:46 MSK
Warning: 192.168.1.1 giving up on port because retransmission cap hit (0).
Nmap scan report for 192.168.1.1
Host is up.

PORT     STATE    SERVICE
3333/tcp filtered dec-notes

Nmap done: 1 IP address (1 host up) scanned in 1.06 seconds
Starting Nmap 7.93 ( https://nmap.org ) at 2024-10-12 22:46 MSK
Warning: 192.168.1.1 giving up on port because retransmission cap hit (0).
Nmap scan report for 192.168.1.1
Host is up.

PORT     STATE    SERVICE
4444/tcp filtered krb524

Nmap done: 1 IP address (1 host up) scanned in 1.06 seconds
The authenticity of host '192.168.1.1 (192.168.1.1)' can't be established.
ED25519 key fingerprint is SHA256:K8TLHMOPXAMq3B3U+8/xYC0CMIlxm/7Cg43eYVLhqEQ.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:1: [hashed name]
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.1.1' (ED25519) to the list of known hosts.
vagrant@192.168.1.1's password: 
Linux inetrouter 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Sep 30 11:45:32 2024
[?2004h]0;vagrant@inetrouter: ~[01;32mvagrant@inetrouter[00m:[01;34m~[00m$ exit
[?2004lвыход
Connection to 192.168.1.1 closed.
[?2004h]0;vagrant@centralrouter: ~[01;32mvagrant@centralrouter[00m:[01;34m~[00m$ [?2004l
выход
Connection to 192.168.121.11 closed.
7]2;max@localhost.localdomain:~/vagrant/vg3]1;localhost.localdomain8max@localhost:~/vagrant/vg3> wget 192.168.1.17h192.168.1.17t192.168.1.17t192.168.1.17p192.168.1.17:192.168.1.17/192.168.1.17/192.168.1.17[C[C[C[C[C[C[C[C[C[C[C[C:8080
--2024-10-12 22:47:45--  http://192.168.1.17:8080/
Подключение к 192.168.1.17:8080... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 200 OK
Длина: 615 [text/html]
Сохранение в: «index.html.1»

index.html.1                                      0%[                                                                                                       ]       0  --.-KB/s               index.html.1                                    100%[======================================================================================================>]     615  --.-KB/s    за 0s      

2024-10-12 22:47:45 (47,5 MB/s) - «index.html.1» сохранён [615/615]

7]2;max@localhost.localdomain:~/vagrant/vg3]1;localhost.localdomain8max@localhost:~/vagrant/vg3> exit
exit

Script done on 2024-10-12 22:47:54+03:00 [COMMAND_EXIT_CODE="0"]
